# Generated by Django 5.2.8 on 2025-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_products_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
