# Generated by Django 5.2.8 on 2025-11-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.AlterField(
            model_name='customer',
            name='signup_date',
            field=models.DateField(auto_now=True),
        ),
    ]
