# Generated by Django 5.2.8 on 2025-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customer_managers_remove_customer_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='signup_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
