# Generated by Django 5.2.8 on 2025-12-08 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_session',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
